version: '3.8'
services:
  assessment:
    image: mrksdh/assessment
    container_name: assessment
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - app-network

  java-app:
    build: .
    container_name: java-app
    depends_on:
      - assessment-service
    network_mode: service:assessment-service
      
networks:
  app-network:
    driver: bridge
