version: '3.8'
services:
  assessment:
    image: mrksdh/assessment
    container_name: assessment
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - app-network
      
  java-apps:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java-app
    restart: "no"
    ports:
      - 8081:8080
    depends_on:
      - assessment
       
networks:
  app-network:
    driver: bridge
