name: Docker Assessment Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-assessment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - name: Pull Docker Image for Assessment
        run: docker pull mrksdh/assessment

      - name: Run docker-compose containers
        working-directory: calculator
        run: docker-compose up -d

      - name: Test API funktion
        run: |
          sleep 10
          curl http://localhost:8080/v1/health
      - name: Shutdown Docker Compose
        working-directory: calculator
        run: docker-compose down
