version: '3.8'
services:
  assessment-service:
    image: mrksdh/assessment
    container_name: assessment-service
    ports:
      - "8080:8080"
    networks:
      - myNetwork

  java-app:
    build: .
    container_name: java-app
    depends_on:
      - assessment-service
    environment:
      - DATASET_SERVICE_URL=http://assessment-service:8080/data
      - RESULT_SERVICE_URL=http://assessment-service:8080/result
    ports:
      - "8081:8080"
    networks:
      - myNetwork

networks:
  myNetwork:
    internal: true
